### ISSUE TITLE
Color value JSON

### ISSUE THREAD

**Issue by F50Ci37Y** [larscom/monokai-dark-vibrant#1]
Thank you for grate theme
![Screenshot from 2019-04-25 17-17-28](https://user-images.githubusercontent.com/20030910/56737205-26bdef00-677f-11e9-9203-4c6e10b8fd6d.png)
 The color value its nor different

**Comment by larscom** [comment]
Hi, thanks for reporting.
I will patch this asap.

**Comment by larscom** [comment]
is fixed in v2.0.3
