### ISSUE TITLE
Hyper Theme?

### ISSUE THREAD

**Issue by drewswaycool** [larscom/monokai-dark-vibrant#2]
Would love a matching theme for Hyper.

**Comment by larscom** [comment]
Hi, can you provide an example with file extension included? I will see what i can do

**Comment by drewswaycool** [comment]
Hey @larscom sorry my comment was somewhat vague. I meant a theme for the electron based terminal replacement https://hyper.is/

**Comment by larscom** [comment]
aha, but thats not something you can do within VSCode right?

**Comment by drewswaycool** [comment]
I've not made a theme for Hyper before, but this tool looks useful. https://www.npmjs.com/package/themer
If you don't get around to it, that's fine. I may investigate this myself if you don't mind.

**Comment by larscom** [comment]
As this is not part of VSCode, i can't help you sorry :) But let me know if you have created a matching theme! Would like to try it out.
